### ISSUE TITLE
Feedback on deliverable D2 ghg concentrations

### ISSUE THREAD

**Issue by vnaik60** [climate-resource/CMIP-GHG-Concentration-Generation#58]
Hi @znichollscr ,

Thank you for sharing the first draft of the full suite of ghg concentration dataset. I had a quick look at the global-, hemispheric-means, so providing feedback for the next iteration. My script and plots are [here ](https://github.com/vnaik60/evaluate_cmip_forcingdatasets/blob/main/ghg/compare_ghgconcs.ipynb). Also tagging @durack1. 

1. GHG names - a mix of chemical and complex names are used for the species, which itself is not a problem, but creates issues when comparing with CMIP6 data for example. Not a deal-breaker but some consistency in chemical formulas and names for the CMIP6Plus datafiles would be helpful. 
2. Sector - it was actually very helfpul to have this as a dimension name rather than "region" as I suggested before (discussed [here ](https://github.com/climate-resource/CMIP-GHG-Concentration-Generation/issues/28)and [here](https://github.com/climate-resource/CMIP-GHG-Concentration-Generation/issues/29)). CMIP6 files also used sector which made it very easy to compare. I suggest sticking with this dimension name for maintaining backward compatibility but defining it in a better way (CMIP6 example is provided [here](https://github.com/climate-resource/CMIP-GHG-Concentration-Generation/issues/28#issue-2291292372))
3. Temporal resolution - just to confirm that your data starts from year 1 and not year 0. CMIP6 started with year 0. 
4. Time dimension - xarray had trouble decoding the time variable but that was also true for CMIP6 files. We are already discussing time [here](https://github.com/climate-resource/CMIP-GHG-Concentration-Generation/issues/29). 
5. Float versus double - this is where there is significant difference between CMIP6 and your files. The precision of the data variable in your files is higher ("double") than in CMIP6 ("float"). Some nearly 0 values show up as very small negative values. Any particular reason you prefer double? 
6. Concentrations - there are small differences in the actual values for the species I looked at. This issue was disucssed for methane [here ](https://github.com/climate-resource/CMIP-GHG-Concentration-Generation/issues/31). 

Best,
Vaishali

**Comment by znichollscr** [comment]
Thanks @vnaik60, super helpful! Going through the points

> GHG names

Here I tried to follow the CF standards (https://cfconventions.org/Data/cf-standard-names/current/build/cf-standard-name-table.html). They are a bit all over the shop, but I assume we're a bit limited in what we can do?

> Sector

Ok. Given the conversation in #29, I'm pretty sure that sector is the wrong use. I can see the backwards compatibility point though so I'm happy to do either (it doesn't matter too much to me, I would prefer to do region and just provide scripts to help people compare but if we have to maintain backwards-compatibility, that can be done).

> Temporal resolution

Yes data starts in year 1. I got rid of year 0 because it doesn't exist in most calendars so it made all sorts of things explode.

> Time dimension

Hmm I'm puzzled by why xarray is struggling with this. I will investigate. x-ref #59

> Float versus double

Ooops, that's just me not paying attention. I can round back to float

> Concentrations

Yep. Some are to be expected but now I need to go back and check more carefully what is going on.
